### ISSUE TITLE
PotPlayer / EVR / 10-bit

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#75] opened 2022-05-25 20:36 UTC
So I know EVR is not good in 10-bit playback... and still Daum PotPlayer allows it.  If it's set to EVR (which is by default) and you play 10-bit video, everything is connected in P010 and looks good.
The problem it's now NOT so good starting with AVSF 1.4.0.
No SVP, no script, just an empty AVSF --> the video is totally unwatchable, like 1-2 fps. Any video - tried both 4K and 720p.
Plays fine with AVSF 1.3.1.

**Comment by CrendKing** [comment] 2022-05-26 01:21
Not sure why the combination of PotPlayer+EVR would cause this issue, since PotPlayer doesn't allow debugger to attach. The reason is https://github.com/CrendKing/avisynth_filter/commit/ff84cb4674d4384f4d567f3b44691cd3ac5b6c69, which I implemented true P010 by bit shifting. We know the function itself is fine since it works in all other combinations. Could be something specific to PotPlayer.

If you really want to use P010 in PotPlayer EVR, maybe ask the player author. Otherwise, if you just want to get back to the 1.3.1 behavior, uncheck P010 from AVSF input format.

**Comment by chainikdn** [comment] 2022-05-26 06:59
> We know the function itself is fine since it works in all other combinations.

Not so sure about it... I have at least one complain where user with i3-8100 claims that 1.3.1 performance is significantly better than 1.4.2, even with madVR.

> if you just want to get back to the 1.3.1 behavior, uncheck P010 from AVSF input format

Nope, EVR won't connect in P016.

Actually I was thinking about a registry option to completely disable shifting and return to old behavior...

**Comment by chainikdn** [comment] 2022-05-26 13:29
> Well, there is no magic here. 

"significantly better" to the point where 1.4.2 is basically unusable and the user had to revert back to 1.3.1
In this case, my vote is for "hack" :D

**Comment by CrendKing** [comment] 2022-05-27 01:56
I did some tests and figured out t

**Comment by CrendKing** [comment] 2022-05-27 03:34
I did some tests. It turns out that when EVR allocates for a sample, the memory buffer of the sample has PAGE_WRITECOMBINE protection, whereas madVR's sample does not. Pages with PAGE_WRITECOMBINE is optimized for sequential write performance, with the cost of severe read performance. The current implementation of the bit shift function is the only function that would read destination buffer. That's why only EVR + 10bit has the issue.

Simple solution would be to allocate temporary buffer without PAGE_WRITECOMBINE, do the bit shifting, then copy the result to EVR's sample buffer. I verified this working. I'm wondering if there's better solution (e.g. could I change that memory page's protection flag when bit shift is needed).

**Comment by CrendKing** [comment] 2022-05-27 04:39
Try https://github.com/CrendKing/avisynth_filter/actions/runs/2394598935

This is specific to EVR. I can reproduce the issue in MPC-BE as well.

**Comment by chainikdn** [comment] 2022-05-27 08:33
Yeah, this seems to work.

However, I don't like the whole idea of doing something for nothing. And here we actually do a lot of work, especially in cases like 4K 24->120 fps. Again, for nothing. Just for the abstract internal beauty.
Can we add some way to bypass the conversion at all? A parameter to AvsFilterSource() looks like a good place. Something like
`AvsFilterSource(dirtyHackCrendKingDoesntLike=true)`

**Comment by CrendKing** [comment] 2022-05-27 08:57
Well, folks from https://github.com/CrendKing/avisynth_filter/issues/65 somehow had their SVP expecting P10, not having ConvertBits(16) in their generated script, and end up having green screen. I don't know if SVP has updated to address that issue, but other users of this filter could be confused of this as well, should I revert https://github.com/CrendKing/avisynth_filter/commit/ff84cb4674d4384f4d567f3b44691cd3ac5b6c69.

My point is, we now have a version that works reasonably OK without the need of a hack, which is good. Unless you can demonstrate a real need of that hack to overcome the benefit of being hackless, I think it's time to close the issue. I really don't think we are doing something for nothing.

**Closed by CrendKing** 2022-05-27 08:57 UTC
Labels: bug

**Comment by chainikdn** [comment] 2022-05-27 09:16
#65 was about Vapoursynth Filter. Which is not a "built-in" way to use SVP. And the solution was simple, w/o the need for adding this conversion: https://github.com/CrendKing/avisynth_filter/issues/65#issuecomment-1065145456

> Unless you can demonstrate a real need of that hack to overcome the benefit of being hackless

> I have at least one complain where user with i3-8100 claims that 1.3.1 performance is significantly better than 1.4.2, even with madVR ... to the point where 1.4.2 is basically unusable and the user had to revert back to 1.3.1

If there's one user => there are many.

> other users of this filter could be confused of this as well, should I revert https://github.com/CrendKing/avisynth_filter/commit/ff84cb4674d4384f4d567f3b44691cd3ac5b6c69

I'm not asking you to revert, I'm asking to add a bypass option.

**Comment by CrendKing** [comment] 2022-05-27 09:21
> I have at least one complain where user with i3-8100 claims that 1.3.1 performance is significantly better than 1.4.2

I'm happy to take a look at the user's claim, if he can come here and provide info, such as log and sample video. If it is proved to be a big problem, I'm happy to add an option to return the old behavior.

**Comment by chainikdn** [comment] 2022-05-27 09:24
dunno why you want  a prove for that you actually know by yourself? 

`Well, there is no magic here. The function does shift every 16-bit integer for each frame, even with SIMD if available. The larger the video size is, the slower.`

indeed, no magic that doing an additional (and unnecessary) work make it slower

**Comment by CrendKing** [comment] 2022-05-27 09:33
What I meant there is the function is not zero cost. It is linear to the video size. However, comparing to the bit shifting function, the deinterleave and interleave are much more costly. It's hard to believe adding the bit shift would suddenly make smooth playback to be unbearable. Most of the time, either the user's computer has a lot of headroom, so adding bit shifting is ignorable cost, or the computer already suffers, so adding bit shifting is also inconsequential. The only case where it make sense is that computer is right at the edge of processing 24fps with near 100% CPU. That's why I want to know what causes the big difference. There could be other factor or bug that is the root cause, just like this one with PAGE_WRITECOMBINE.

**Comment by Overtone3** [comment] 2022-05-27 10:47
Hello,
I have been expriencing this issue (i3-8100, Geforce GTX 1060 3GB, 8GB Ram.)
SVP 4 worked perfectly using PotPlayer + AVISynth 1.3.1 + default rendered all the way up to recent update. Recent update resulted in color issues (using all other non madVR renderers) and performance loss using madVR + SVP.
After corresponding with SPV's (awsome!) support, I had to revert back to 1.3.1 after experiencing performance issues with *all* renderers (including madVR) following recernt update.
madVR also experienced much less smooth playback following recent update. It worked, but took time loading after fast forwarding or any skip during playback.

I hope this is helpful 🙏👍

**Comment by CrendKing** [comment] 2022-05-27 12:15
Could you open a new issue, follow the issue template. Some screenshots for color problem, [log](https://github.com/CrendKing/avisynth_filter/wiki/How-to-enable-logging) and sample video to reproduce the symptom would be very helpful.

This ticket is for EVR 10-bit problem, and a patch has been provided. So let's close this issue.

**Comment by chainikdn** [comment] 2022-05-27 12:25
please, don't mess things up
there's no "color problem", I'm only talking about _performance_ issue introduced with this "10-bit shifting"

**Comment by CrendKing** [comment] 2022-05-27 22:27
I was referring to Overtone3's comment:

> Recent update resulted in color issues (using all other non madVR renderers)

I'm yet to see number of support this so called "performance issue".

**Comment by chainikdn** [comment] 2022-05-28 09:20
is it possible that the code goes the wrong path (i.e. non-AVX2) on i3-8100?
may be adding a few perf. counters to the log output will be a good idea?

---
"color issue" is about ConvertBits(16) in SVP's script is not compatible with AVSF 1.4.2 when using EVR, so just forget about it

**Comment by CrendKing** [comment] 2022-05-28 09:22
Sure. I'll add a few more logs.

Thanks for clarifying the color issue.

**Comment by chainikdn** [comment] 2022-05-28 20:31
soo... it's like 5-7 ms per 4K frame, am I correct? 
input thread: (3 ms deintreleave + 6 ms shift) * 24 fps
output thread (one thread!!!): (5 ms interleave + 6 ms shift) * 60+ fps

**Comment by CrendKing** [comment] 2022-05-28 21:32
Again, log and sample video.

**Comment by chainikdn** [comment] 2022-05-29 08:32
https://4kmedia.org/ultra-hd-hdr-samsung-4k-demo-wonderland/
[avsf.log](https://github.com/CrendKing/avisynth_filter/files/8792917/avsf.log)

**Comment by CrendKing** [comment] 2022-05-29 23:44
I tested the same video and here's the average numbers I'm seeing:

No-op script:
Log: [no-op.log](https://github.com/CrendKing/avisynth_filter/files/8794513/no-op.log)
Deinterleave: 1ms
Interleave: 1ms
Right shift: 2ms
Left shift: 1.5ms
CPU: 5% total (Ryzen 5800X), using AVX2
LAV hardware decoding is set to D3D11 (I think it's reasonable to expect user enabling hwdec for 4K videos).

After enabling SVP (doubling 24fps to 48fps):
Log: [svp.log](https://github.com/CrendKing/avisynth_filter/files/8794519/svp.log)
All stats from AVSF are still the same
CPU: 25% total
Still able to maintain stable 48fps output

I think these numbers are very reasonable. Since all these functions basically go through each pixel and do some SIMD stuff, they should have approximately same cost. I don't think adding 3ms is a big deal for 4K.

And since it's madVR we are talking about here, if you really don't like the shifting, just untick P010 and P210. According to my test, with SVP enabled, P010 has at most 1% CPU overhead in my environment comparing to P016.

**Comment by chainikdn** [comment] 2022-05-30 09:35
> Still able to maintain stable 48fps output

No doubt Ryzen 5800X is a good CPU and this additional overhead doesn't hurt it at all. Sadly not anyone have 5800X...
Lets ask [Overtone3](https://github.com/Overtone3) for a 8100 numbers.

**Comment by Overtone3** [comment] 2022-06-04 04:38
Hello,

I am still experiencing image and performance issues using EVR and SVP 4.0. 
I know I don't have the strongest system in the world but used to play 4k videos @60fps until recent updates. (and also I thought Gefore GTX 1060 3GB should compensate somewhat for weak CPU no?)
I am happy to share addtional information but might need some guidance on which data and how to generate it.
I am attaching SVP 4.0 event log + [SVP log.txt]
(https://github.com/CrendKing/avisynth_filter/files/8837037/SVP.log.txt)
![EVR + SVP 4 0](https://user-images.githubusercontent.com/106381127/171983210-1aa64df6-c62e-41c2-b106-f3718ddd542c.png)
![EVR (Autoselected) + AVISynth1 4 2 HDR 10bit ](https://user-images.githubusercontent.com/106381127/171983212-0023195c-9e62-4acd-97ed-b32b92242b21.png)
 What else can I share?
[SVP log.txt](https://github.com/CrendKing/avisynth_filter/files/8837030/SVP.log.txt)

**Comment by Nuihc88** [comment] 2022-06-04 08:59
@Overtone3 You can enable AviSynth Filter's logging by following the instruction [on this wiki page](https://github.com/CrendKing/avisynth_filter/wiki/How-to-enable-logging).

**Comment by chainikdn** [comment] 2022-06-04 09:22
@Overtone3 remove that "quick fix" from generate.js. Current solution is this:
- P010 unchecked in AVSF properties
- SVP always use P016 (i.e. ConvertBits(16) in the script)

And now you probably have P010 unchecked but ConvertBits(10) --> "image issues" with EVR.

**Comment by Overtone3** [comment] 2022-06-05 01:29
Hi,

**Nuihc88** - I followed the instruction on the wiki page, but for some reason no log file is being generated in my path folder after watching videos on PotPlayer... I am not sure what am I doing wrong.  I did the whole registry thing and restarted but that didn't help. Any idea what I could be missing?

**Chainikdn** - thanks, "quick fix" was already reversed when I posted the previous screenshots. Indeed, P010 is unchecked in AVSF. 
Sorry, I am not sure I understand the second bullet point. In the script,  "ConvertBits" is mentioned twice. One is the quick fix line which is now back to 16 and the other is:
res += bl+'input_m8 = '+(media.p10 ? 'input_m.ConvertBits(8)':'input_m')+br;
which I didn't touch.

**Comment by CrendKing** [comment] 2022-06-05 06:18
Hi, Overtone3. It might be dumb, but please disable AVSF and check if there is color issue. Make sure AVSF doesn't show up in context menu -> Filters.

Log file should be created if everything worked as expected. Does AVSF show up in menu -> Filters?

Is there particular reason you don't use madVR for 10-bit content? It supports all kinds of video formats and usually results in better performance.

Also, what's the format of the video? Is it 4:4:4 and 10 bit? Or just 4:2:0? Does your GPU support HW decoding HEVC?

**Comment by Overtone3** [comment] 2022-06-06 08:16
Hi,

No color issues when disabling AviSynth.
Yes, AviSynth, does show up in menu. 
I am happy to use madVR, however, I am experiencing the same performance issues playing 4k videos using madVR + SVP (no color issue though).
I am using Gefore GTX 1060 3GB which supports HEVC decoding (most videos that I watch are HEVC).
My video card output color format is 4:2:2. Videos' color format is 4:2:0.

BTW - I noticed that when starting playback using EVR + SVP, and then switching to madVR -- the color issue prevails. Restarting PotPlayer with madVR resloves the colost issue, although, still struglling playing 4k videos due to performance issue.
 🙏

**Comment by chainikdn** [comment] 2022-06-06 12:06
This is because of "10-bit output" checked in PotPlayer preferences (Video section).

**Comment by CrendKing** [comment] 2022-06-07 05:14
I noticed that YUY2. Usually it is there because EVR only support YUY2 beyond 4:2:0 10 bit. For example, if you play 4:2:2 10 bit, or 4:4:4 16 bit, all are downgraded to YUY2.

AVSF supports YUY2. Not sure why there is color issue for you without log.

![Clipboard 1](https://user-images.githubusercontent.com/975235/172300974-02905ba8-3f13-4e85-9e2e-676f8957762c.jpg)

**Comment by Overtone3** [comment] 2022-06-07 08:48
Hi!
So unchecking the "10-bit output" under video settings resolved both the color and performance issue, but doesn't that mean that 10bit videos are now presented at 8bit?

I don't really know what to do regarding the YUY2 subject you mentioned.

I tried again to log AviSynth but no luck. Adding here my registry screenshots. What am I doing wrong?

![image](https://user-images.githubusercontent.com/106381127/172337432-fdbff4e2-bf10-49db-97d4-b61efc650b70.png)
![image](https://user-images.githubusercontent.com/106381127/172337519-807e10d3-5cf7-425f-8efa-c14d65a42093.png)

Cheers!

**Comment by Overtone3** [comment] 2022-06-07 12:13
Ok chainikdn, you were spot on regarding the writing to c drive. I was able to generate AviSynth logs. :)
Attaching two of them - one using madVR with HDR output and one using EVR.
EVR had fairly good performance without dropping frames.
madVR interestingly dropped frames only when on full screen mode.
Sorry, but if the video is converted to 8-bit, doesn't that mean that I lose color data? I would very much like to view the videos in their full orifinal 10-bit format... :\

[avisynth_filter - madVR.log](https://github.com/CrendKing/avisynth_filter/files/8853032/avisynth_filter.-.madVR.log)
[avisynth_filter - EVR.log](https://github.com/CrendKing/avisynth_filter/files/8853034/avisynth_filter.-.EVR.log)

**Comment by chainikdn** [comment] 2022-06-07 15:00
> Sorry, but if the video is converted to 8-bit, doesn't that mean that I lose color data?

sure you do

EVR doesn't want P016
P010 implies conversion in AVSF --> "performance issue"
so I'd say let madVR decide how to render P016 video. dunno what exactly does that PotPlayers' "10-bit" switch but I'm sure it's not needed for madVR.

**Comment by CrendKing** [comment] 2022-06-08 07:02
From the first two logs, were you playing regular 4:2:0 8 bit video, because the formats are NV12 -> NV12? And EVR is fine while madVR drops frames in full screen? What's the video?

3rd log is from 10 bit video (P010 -> P010). What's the video? You are saying EVR has issue but madVR is fine?

**Comment by Overtone3** [comment] 2022-06-08 09:09
Hi,

Ok,
1. I replaced the contents of C:\Program Files (x86)\SVP 4\avsf with the one in CrendKing's link (no dll file in there so replaced all other overlapping files)
2. "From the first two logs, were you playing regular 4:2:0 8 bit video, because the formats are NV12 -> NV12?" --- No, I only played 10-bit videos. Not sure why the log file shows 8-bit..
3. "And EVR is fine while madVR drops frames in full screen?" -- Correct.
5. What's the video? Bosch.Legacy.S01E01.2160p.AMZN.WEB-DL.x265.10bit.HDR10Plus.DDP5.1-FREESHIT[rartv]
6. Adding that The 10-bit output option is grayed out when switching to madVR. Frankly, I am happy to swicth permanently to madVR if it is better.
7. Ok,,  I figured out that in Poyplater > Prefrences > Corospaces > Output color space was set on "Auto (Recommended)" which might resault in that converion to 8-bit. When changing it to P010 - YUV 420 Plain 10 Bits, video are displayed in 10-Bit format as per PotPlayer. However, performance using madVR are isgnificantly worst. EVR displays the same color issues using this setting.
![P010 + madVR ](https://user-images.githubusercontent.com/106381127/172578413-645f462a-5c0e-4ba6-a3c7-4bd77dfbe886.png)

**Comment by CrendKing** [comment] 2022-06-09 08:28
Thanks for the info.

1. Thanks to the video name, I now can (almost) replicate your environment. Basically the video is 4:2:0 10-bit HDR encoded with H.264. You are using PotPlayer's built-in codecs (instead of [LAV Filters](https://github.com/Nevcairiel/LAVFilters/)).
2. I can confirm that if that PotPlayer's colorspace setting is Auto, PotPlayer prefers to give AVSF NV12 output from its built-in codec. This is how it works internally: when the player initially launches, it tells AVSF the list of formats it can outputs. Then AVSF tells the player what AVSF supports based on that input list. Lastly, **the player chooses** which format it outputs. What's weird is, AVSF tells the player it supports P010, but PotPlayer still chooses NV12. But if the codec is directly connected to the renderer (EVR/madVR), it outputs P010. So there could be some magic in the format negotiation logic, but since PotPlayer is closed source there is no way for me to fix it. On the other hand, LAV Filters works as expected.
3. I can't reproduce the issue you describe. madVR in fullscreen does not drop frames with AVSF. Since the video is HDR, and I believe EVR doesn't support HDR while madVR does, this could be issue specific to how your system handles HDR in fullscreen. It could be driver related.

At the point I suggest you:
1. Update NVIDIA driver if not latest.
2. First try LAV Filters in PotPlayer, see if anything changes.
3. If not, try LAV + madVR in MPC-BE/MPC-HC. You don't have to stick to it, just an experiment.

**Comment by Overtone3** [comment] 2022-06-13 05:01
Hi,
Thanks again.
I updated NVIDIA drivers but no change.
Installed LAV filters and used in PotPlayer. See below configuration data and results. Bottom line is I am still experiencing performance issues viewing HDR using madVR.

I tried DmitriRender (without SVP nor AVSF) as well which leads to the same result. I am beginning to this this is a madVR issue..

I'm lost.. 


![P010 + madVR ](https://user-images.githubusercontent.com/106381127/173281673-3112a632-a4c6-4bff-9561-c4d8616061c7.png)

![Screenshot 2022-06-13 143901](https://user-images.githubusercontent.com/106381127/173281664-703b4d6e-089b-4818-a84f-e51a76a6578d.png)

![Screenshot 2022-06-13 144037](https://user-images.githubusercontent.com/106381127/173281639-a3737dfc-5a95-47e4-8e52-040c2ae2383d.png)

**Comment by CrendKing** [comment] 2022-06-13 11:06
> I am beginning to this this is a madVR issue

If I'm allowed to bet on this one, I place my chips on PotPlayer. Have you tried MPC-BE?

**Comment by Overtone3** [comment] 2022-06-17 12:27
Ok, so I tried MPC-BE + madVR + FFDdhow filters and got the exact same result.
Using madVR I was able to generate 10bit outout but experienced performance issue viewing 4K videos.

![Screenshot 2022-06-17 221552](https://user-images.githubusercontent.com/106381127/174297950-27428197-d8d5-4243-9c3a-f065a999e638.png)

**Comment by chainikdn** [comment] 2022-06-17 12:37
I'm lost 🤣 
"MPC-BE + madVR + FFDdhow" won't give you 10-bit cause ffdshow is 8-bit only
AVSF + madVR: for ver. 1.4+ you must have "P010" checkbox **unchecked** in AVSF properties, and madVR will show P016 in this case ---> this must work as fast as AVSF ver.1.3 + P010

**Comment by CrendKing** [comment] 2022-06-17 18:50
> MPC-BE + madVR + FFDdhow filters and got the exact same result.

Probably something is wrong with your environment at this point.

> in fact I'm ready to deploy custom AVSF build with this P010-bit-shifting disabled when RC is connected.

Feel free to fork if you think that bit shift is such a big deal. My stand is still that until concrete proof shows up I believe it's minimum impact.

**Comment by chainikdn** [comment] 2022-06-17 19:06
> My stand is still that until concrete proof shows up I believe it's minimum impact.

leave 4 cores w/o HT instead of 8 cores + HT and you'll see the impact

**Comment by CrendKing** [comment] 2022-06-17 19:10
Unfortunately I don't have a CPU with 4 cores. I can only see what I can see. Why don't you ask some of your SVP customers with that configuration to come here, show me some screenshots and logs that prove impact, and I'll happily provide that option you ask for.

Is what I'm asking unreasonable?

**Comment by chainikdn** [comment] 2022-06-17 19:11
> I don't have a CPU with 4 cores

you can use Ryzen Master or BIOS settings or even just msconfig.exe ;)

**Comment by CrendKing** [comment] 2022-06-17 19:15
Oh I see what you mean. I'll try that later. But didn't you say this bit shifting is about single core only? Disabling 4 cores or HT does not alter single core performance, no?

> what do you mean? we now have only ONE output thread that does all this stuff

**Comment by chainikdn** [comment] 2022-06-17 19:23
> Disabling 4 cores or HT does not alter single core performance, no?

yeah, but all other computation threads are still here

**Comment by CrendKing** [comment] 2022-06-17 19:39
![Ryzen Master](https://user-images.githubusercontent.com/975235/174391099-670b774b-0151-4260-b429-23e051b93aa6.jpg)

**Comment by CrendKing** [comment] 2022-06-17 23:48
Just did the test.

Environment: MPC-HC + LAV Filters + madVR


total CPU usage:
* Baseline (without AVSF): 39% on average
* 10-bit with bit shifting: 46%
*

**Comment by chainikdn** [comment] 2022-06-18 08:48
> When SVP is enabled (not even going 60, just doubling), the playback is already choppy.

In a real life user would adjust SVP settings so it run well on his computer. "Auto" settings in SVP should keep CPU load at ~70% max (considering the "baseline" is <10%, not 39% as in your test). And now we're replacing AVSF with the newer version which takes additional, lets say, 10% (this is what I saw when playing 4K at 60 fps on 4+HT config). And everything gets broken.

**Comment by CrendKing** [comment] 2022-06-18 10:44
You are saying a system with 4+HT CPU + MPC + LAV + madVR can play 4K with < 10%. I just don't believe you. When I play 720p where the baseline is 10%, the bit shift adds < 1%.

Show me the log and screenshot when bit shifting takes the same amount of CPU as baseline.

**Comment by chainikdn** [comment] 2022-06-18 10:50
> I just don't believe you.

mmm, what's the problem? with a hw video decoder active MPC-HC takes <5% (w/o AVSF)

> stop suddenly adding HT, you literally told me to disable HT earlie

yeah, but I can't disable HT cause I'm on a laptop and msconfig.exe is my only choice

**Comment by Overtone3** [comment] 2022-06-18 11:07
> lost

Hi,
Sorrym just a quick update that:
1. So I tried MPC-BE + madVR + LAV filter + SVP but still experiencing performance issues playing 4k 10bit HDR.
2. Same issue if I uncheck P010 using ffdshow filters.
3. I tried using DmitriRender as an alternative to SVP+AVSF, which works very smoothly actually using my GPU at ~90%. (I was able to generate 10bit output by changing the colorspacing options to P010 in PotPlayer.) When I enable madVR though, things go to shit (DmitriRender doesn't use AVSF).
5. I know I originally had performance issues using SVP+EVR, apparetnly they prevail with madVR as well, but probably not due to system resources (since DmitriRender works great) but maybe AVISynth following recent update?
6. CrendKing - sorry, I am not very familiar with the logging options. Would another AVISynth log help as proof? Do you need me to share a video of the playback?

Thanky you guys again so much for looking into this!!!

**Comment by CrendKing** [comment] 2022-06-18 11:08
> with a hw video decoder active MPC-HC takes <5% (w/o AVSF)

Your definition of "baseline" is without AVSF? OK. AVSF adds 10%. But how much of that is from bit shifting?

**Comment by chainikdn** [comment] 2022-06-18 11:13
>  Tell me how much AVSF adds 10-bit vs 16-bit.

I said - 10%

**Comment by CrendKing** [comment] 2022-06-18 11:17
> So I tried MPC-BE + madVR + LAV filter + SVP but still experiencing performance issues playing 4k 10bit HDR.

If you are experience performance issue without AVSF, you might want to talk to chainikdn here.

> I said - 10%. If it was 70% with smooth playback it's now 80% and choppy. That's the difference.

You are saying, in your laptop with 4+HT, without AVSF, it's using 5% playing 4K. Using old AVSF + SVP it reaches 70% and new AVSF + SVP it reaches 80%, right? What's the number without SVP?

**Comment by Overtone3** [comment] 2022-06-18 11:34
> 

Hi, I only used LAV because you wrote it is recomended. Without it I have color issues as well with MCE-BE. Buttom line is I am experiencing issues when using either SVP+AVSF+Any filter which I didn't have before ACSF recent update I think.
Performance using DmitriRender (excluding madVR) is great, so I don't think this is a hardware issue.
Cheers

**Comment by chainikdn** [comment] 2022-06-18 13:23
base (no AVSF): 8%
base (AVSF 16b): 13%
base (AVSF 10b): 16%

SVP 60 fps, NVOF (10b->10b): 71%
SVP 60 fps, NVOF (10b->16b): 66%
SVP 60 fps, NVOF (16b->16b): 54%

SVP 80 fps, NVOF (16b): 78%
SVP 80 fps, NVOF (10b): nogo, CPU 85%, SVP index <1

SVP 90 fps, NVOF (16b): nogo, SVP index <1

SVP 60 fps (16b): 68% (auto profile #8)
SVP 60 fps (10b): 86%

**Comment by CrendKing** [comment] 2022-06-20 01:55
Overtone3: I'm genuinely confused. You said you have problem with PotPlayer, with LAV and with ffdshow. You said you have problem with EVR and madVR. You said you have problem with and without AVSF. You said you have problem with SVP. The only one without problem is DmitriRender.

Since I can't figure out how to reproduce the issue, I can't help. I suggest you to stay at the last working version for now, until you can gather new info.

chainikdn: For now, I suggest you either fork this project and do whatever you want, or disable 10-bit input format when your users install AVSF bundled with SVP.

If any of you have other concerns, please open a new issue. This one is too long to follow.
