### ISSUE TITLE
Chroma is broken when using LWlibavVideoSource+MPC-HC+AVSF

### ISSUE THREAD

**Issue by Disaer** [CrendKing/avisynth_filter#84] opened 2022-11-19 06:54 UTC
### Environment
- Filter version: `v1.4.5 # 3ec5059`
- AviSynth+ version: v3.7.2 r3661
- OS: Windows 10 x64 [Version 10.0.19045.2251]
- AviSynth script: no
- Log file: https://pastebin.com/nyQs1pS7

### Describe the bug
Chroma is broken when using .avs file with LWlibavVideoSource as source with MPC-HC+AVSF
Note that MPC-BE+AVSF or MPC-HC without AVSF have no this problem

### To Reproduce

1. Create single string .avs file with LWLibavVideoSource as source : `LWLibavVideoSource("BalloonRide.mp4")`
2. Open created .avs file with MPC-HC+AVSF (no script in AVSF is set)
3. Chroma is broken

<img src="https://user-images.githubusercontent.com/32884204/202836917-8b599bf9-98ce-453d-b653-d6dce1764b71.png" width="33%"> <img src="https://user-images.githubusercontent.com/32884204/202836922-54806d52-9615-480d-8886-293a576b1f9f.png" width="33%"> 
Sample video file: https://www.mediafire.com/file/p8d1qm98h83wl8c/BalloonRide.mp4/file

**Comment by flossy83** [comment] 2022-11-20 05:27
Strange, I would have thought AVSF should be doing nothing at all since you have no script set in AVSF.

If you untick AVSF in MPC-HC's External Filters section, does it resolve the issue?

**Comment by flossy83** [comment] 2022-11-20 05:46
Ok, I am able to reproduce it now.  Seems to be an issue with MPC-HC's internal LAV filter, as I can resolve it by unticking Avisynth in settings > internal filters > source filters (on my system this causes MPC-HC to use Microsoft's "AVI Wav/File Source" filter for opening .avs files).

Another way of resolving it is to simply untick "enable remote control" in AVSF to remove it from the list of active filters during playback.

**Comment by CrendKing** [comment] 2022-11-22 23:52
If you do not use `AvsFilterSource()` as your source, you are not using this filter. You are using the avs support from the video player. In this case, you should disable AVSF in the player.

> untick "enable remote control" in AVSF

When you don't specify an avs file in AVSF, AVSF should automatically disconnect itself from filter graph, unless "enable remote control" is ticked. Unticking it is the way to go.

**Comment by CrendKing** [comment] 2022-11-29 01:37
Assuming you get the answer. Feel free to re-open if needed.

**Closed by CrendKing** 2022-11-29 01:37 UTC
Labels: bug
