### ISSUE TITLE
Playback freezes on some content after a few frames

### ISSUE THREAD

**Issue by mark007** [CrendKing/avisynth_filter#24] opened 2020-11-12 20:44 UTC
### Environment
- Filter version: 0.8.1
- AviSynth+ version: AviSynth+ 3.5 (r3106, 3.5, x86_64)
- OS: Windows 10 x64
- Video player: mpc-be 1.5.5 (build 5274) beta
- Splitter filter and video decoder: LAV Filters latest nightly 0.74.1.87-git
- Video renderer: madVR latest 114 beta
- Video format: NV12
- AviSynth script: No script at all
- Do you use other DirectShow filters? Specify name and version: XySubFilter 3.1.0.752

### Describe the bug
An issue which I assume also somehow related to the frame queue/cache. When madVR is set (as I have it set) to "delay playback start until render queue is full", and "delay playback start after seeking, too", sometimes (perhaps 50% of the time, but I can't find a pattern), when starting some videos, the image plays a few frames and then freezes. I have gpu and cpu queue set at 16 now. The audio continues in the background fine.

Manually seeking in the file, restores video playback.

Changing display modes (by double clicking madVRs image and letting it change my desktop from default of 60 to 48hz) seems to completely stop the audio.

This clip is an interlaced clip that I'm using LAV Video Yadif to de-interlace to double its original frame rate. (its a live performance of Lady Gaga Born This Way titled "Born This Way - 2011(HDTV-1080).mpg")

This occurs without SVP enabled (exited from the system tray completely), so avisynthfilter in this case has no actual avisynth script to process.

### To Reproduce
1. Play clip
2. Wait about 0.5 seconds
3. The image freezes but audio continues

**Checklist**
- Did you try a different **video player** and check if the issue persist? For example, if your main video player is MPC-HC, try MPC-BE.
Answer: No

- Did you try a different **video renderer** and check if the issue persist? For example, if issue exists with madVR, try EVR.
Answer: Yes I tried EVR, and can't reproduce there. It seems like some combination of madVR and avisynthfilter from what I can see.

- Did you try a different **video file** and check if the issue persist? Try another file with different format, dimension and frame rate.
Answer: Yes, I am currently only able to reproduce it on this 1 file. I'll try other HFR files to see can I reproduce also.

**Comment by mark007** [comment] 2020-11-12 20:47
[avisynth_filter.zip](https://github.com/CrendKing/avisynth_filter/files/5533224/avisynth_filter.zip)

**Comment by CrendKing** [comment] 2020-11-13 05:59
If only one video file has the issue, I'll need that file. Don't upload copyrighted videos here though.

**Comment by mark007** [comment] 2020-11-14 01:31
> If only one video file has the issue, I'll need that file. Don't upload copyrighted videos here though.

sent you a PM on doom9 with a sample @CrendKing

**Comment by CrendKing** [comment] 2020-11-14 05:52
I can't legally download videos from torrent sites. I tried interlaced videos from https://forum.videohelp.com/threads/388984-How-to-best-de-interlace-and-work-this-samples-out with the same setup in LAV and madVR. Can't cause any crash or freeze.

If you can find un-copyrighted video that has the symptom, please let me know.

**Comment by CrendKing** [comment] 2020-11-23 03:46
I tried my best to replicate your setup, but I can't get any freeze. The only things I don't have are madVR beta 114, which I can't find and thought it is some dynamic tone mapping data on top of 0.92.17, and XySubFilter which I don't think matters since the video has no subtitle. There's about 0.5 second delay at beginning, but never completely freeze. Also, your log file shows everything was working as expected. Could be a madVR bug. Try with the stable version.

**Comment by Nuihc88** [comment] 2020-11-23 04:39
I got curious and did a quick search for the beta version of MadVR mentioned and found the following link:

http://madshi.net/madVRhdrMeasure114.zip

Haven't tested it myself, but it seems to contain the aforementioned binaries.

**Comment by CrendKing** [comment] 2020-11-23 05:00
Thanks. But that version seems only change some HDR stuff, unrelated to seemingly freezing problem.

**Comment by mark007** [comment] 2020-11-23 20:37
I have gone back to the latest stable madVR version now, 0.92.17, but it persists for this clip. I will see if madshi can take a look, but as this is the first filter that has ever exhibited an issue like this with madVR for me, I'm really not sure where to take it. Its one of those strange ones that's a combination of multiple factors, maybe multiple filters that causes it.

**Comment by CrendKing** [comment] 2020-11-24 01:39
BTW, if you remove avsf from the graph, would it never freeze? What if you add ffdshow raw video filter to the graph (let it do some seemingly harmless work, such as cropping)?

**Comment by mark007** [comment] 2020-11-25 18:58
Yeah I have removed it from the graph and reinstalled ffdshow 64 4531 and added the ffdshow raw video filter to the external filters. I can see SVP actually updating its avisynth section and ticking the box for avisynth when playback starts. I also enabled blurring, and tried a few different back / forward buffer sizes in the avisynth section, as I suspect (as a non filter developer of course) that its somehow related to frames/buffers/timestamps somehow.

**Comment by CrendKing** [comment] 2020-11-26 23:25
Am I missing anything?

![1](https://user-images.githubusercontent.com/975235/100396851-a830cf80-2ffb-11eb-9b60-103cfb9c2943.jpg)
![2](https://user-images.githubusercontent.com/975235/100396852-a8c96600-2ffb-11eb-843b-2d4dfebde27e.jpg)
![3](https://user-images.githubusercontent.com/975235/100396853-a8c96600-2ffb-11eb-9512-66d85611616a.jpg)
![4](https://user-images.githubusercontent.com/975235/100396849-a7983900-2ffb-11eb-8fc4-21305c572b2f.jpg)

**Comment by mark007** [comment] 2020-11-27 21:36
Thank you for trying. I have matched your settings exactly and it still happens. What I see on the avisynth filter status page when the freeze happens, it consistently shows the following at the point of the freeze. Whether this means anything in particular, or gives a clue I'm not sure :(

Frame Numbers: 580 -> 578 -> 578
Input buffer size: 2
Output buffer size: 0

**Comment by CrendKing** [comment] 2020-11-28 03:27
I managed to reproduce the crash/freeze with this extremely specific setup. Some CPU queue size from madVR trigger crash, as you documented, with 14 as the threshold number. And there is a format change after the 15th frame. GPU queue size or AviSynth version don't seem matter.

Interestingly, if I insert ffdshow in between LAV and avsf, the crash is gone. Log file shows the difference is that the format change is gone.

I can debug this further and update this comment later, but my initial thought is that this is more likely a bug of madVR handling the combination of events (delay for buffer fill, CPU queue size, format change and deinterlace).

**Comment by CrendKing** [comment] 2020-11-28 16:23
Here is what I discovered so far. When using LAV with your specific setup, after the 15th source frame, it will issue a input format change. avsf will deliver the format change to downstream, which is madVR. If madVR gets this format change BEFORE the CPU queue is full (with the delay option enabled), it freezes.

Now the explanation of why some CPU queue sizes work. Internally, avsf has a buffer size, let's call it X. Currently it is hardcoded as 8. avsf can queue up to this number of source frames ahead of output frames. So assuming the madVR CPU queue size is Y, the math for not freezing is:
```
X + Y < 15
```
In my test, every Y that is less than or equal to 6 does not freeze. When X == 8 and Y == 7, it freezes. If I adjust X to a smaller number such as 7, and increase Y to 8, it also does not freeze. There is a minimum requirement of X equal to 3. So once I increase Y to 12, it always freezes.

Since this bug requires specific configs of at least 2 filters (LAV and madVR), and a specific video. I don't think the root problem is in avsf until further evidence. I'll close for now.

**Comment by CrendKing** [comment] 2021-04-07 06:58
I figured out a way to fix this. Now madVR will not freeze. However, EVR still rarely freezes for some reason. But since we don't have EVR's source code or debug symbol, I guess we won't know why.

**Comment by CrendKing** [comment] 2021-04-14 22:33
Fixed in https://github.com/CrendKing/avisynth_filter/releases/tag/v0.10.0

**Closed by CrendKing** 2021-04-14 22:33 UTC
Labels: bug

**Comment by mark007** [comment] 2021-04-14 22:40
> Fixed in https://github.com/CrendKing/avisynth_filter/releases/tag/v0.10.0

Thank you for the fix!
