### ISSUE TITLE
_AbsoluteTime resets on seek

### ISSUE THREAD

**Issue by FoLLgoTT** [CrendKing/avisynth_filter#85] opened 2022-12-11 19:02 UTC
### Environment
- Filter version: 1.4.5
- AviSynth+ version: 3.7.2
- VapourSynth version: R61
- OS: Windows 10 x64
- Player: MPC-HC 1.9.22.2
- AviSynth script: 

import vapoursynth as vs
import functools

clip = VpsFilterSource

def Shift(n, f, clip, core):
	if f.props._AbsoluteTime > 5.0:
		clip = vs.core.std.AddBorders(clip, bottom=280)
		return vs.core.std.Crop(clip, top=280)
	else:
		return clip

clip = vs.core.std.FrameEval(clip, functools.partial(Shift, clip=clip, core=vs.core), prop_src=clip)
clip = vs.core.std.Crop(clip, 0, 0, 280, 280) 
clip.set_output()

### Describe the bug
_AbsoluteTime is reset on each seek and starts with 0 again. I want to implement a time based pan & scan for multi format movies. For that I need the precise time code of each frame and apply individual cropping or shifting.

I tried it with Avisynth+ and with VapourSynth. The behavior is the same.

**Comment by FoLLgoTT** [comment] 2022-12-11 19:10
I found this issue:

https://github.com/CrendKing/avisynth_filter/issues/82

So I guess it is the same cause and cannot be fixed. :-(

**Comment by CrendKing** [comment] 2022-12-12 00:07
Yes, dupe of #82. Sorry it's by design.

**Closed by CrendKing** 2022-12-12 00:07 UTC
Labels: bug
