### ISSUE TITLE
Couldn't install it

### ISSUE THREAD

**Issue by Shnxxx** [CrendKing/avisynth_filter#28] opened 2020-11-26 03:23 UTC
### Environment
- Filter version: v0.8.1
- AviSynth+ version: 3.6.1_20200619
- OS: Windows 10 x64
- Video player: PotPlayer x64 v201021(1.7.21311)
- Splitter filter and video decoder: LAV Filters
- Video renderer: madVR

### To Reproduce

1.Unzip AviSynthFilter.zip
2.Run as administrator "install.bat" from AviSynthFilter folder.
3.
![image](https://user-images.githubusercontent.com/48496678/100304418-a7874180-2fd9-11eb-848a-ff53bda8e7b0.png)

Am I missing something? Sorry if I opened an issue for this. Don't know where to ask.

**Comment by CrendKing** [comment] 2020-11-26 14:54
Duplicate of https://github.com/CrendKing/avisynth_filter/issues/23

**Closed by CrendKing** 2020-11-26 14:54 UTC
Labels: bug
